default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  <<: *default
  database: crypto_hub_dev

test:
  <<: *default
  database: crypto_hub_test

production:
  <<: *default
  database: crypto_hub_prod
  username: base_vue
  password: <%= ENV["CRYPTO_HUB_DATABASE_PASSWORD"] %>
